### PR TITLE
Preload All Scripts

### LINKED ISSUE #7: Add Preload Link Tags To Head
Because this project does not bundle the output of a build it is importing from links at runtime. We should probably add `<link rel="preload" />` tags in the header for the static output so the browser knows to start fetching those files.

### PR DESCRIPTION
**Pull request by shadowtime2000**
Should resolve #7.

### CODE REVIEW

**Comment by ije** [comment]
- thanks, but consider the `createHtml` is a help function, please add the preload scripts in `project.ts`
- to keep code style, please use vscode default formater: always use `'` for plain string and no `; ` as line end

**Comment by ije** [comment]
in fact all the preload-able scripts will pre-import in main.js(please check it in chrome) and main.js is preloaded, i am wonder maybe no preload scripts needed (should test it)

**Comment by ije** [comment]
and preload script should be `<link rel="modulepreload" src="..." />` since it's an **esm** script

**Comment by shadowtime2000** [comment]
> in fact all the preload-able scripts will pre-import in main.js(please check it in chrome) and main.js is preloaded, i am wonder maybe no preload scripts needed (should test it)

@ije I think you are still going to need to preload those others scripts. Check this snip from the Google Lighthouse:
image

**Comment by ije** [comment]
i see, thanks, do you have a spare time to check the `project.ts`(it's a bit large)? the preload scripts shoud be added in here not `html.ts`, or i will finish it later.

**Comment by ije** [comment]
add preload scripts with `createHtml` function:
```javascript
createHtml({
            ...
            scripts: [
                {src: '...', type: 'module', preload: true},
                ...
            ],
            ...
        })
```

**Comment by shadowtime2000** [comment]
I will take a look at it.

**Comment by ije** [comment]
cool!

**Comment by shadowtime2000** [comment]
@ije I moved the changes to `project.ts`.

**Comment by ije** [comment]
@shadowtime2000 i would create a function like:
```typescript
function getPreloadScripts(baseUrl: string) {
    const scripts = [
        `-/deno.land/x/aleph/aleph.js`,
        `-/deno.land/x/aleph/context.js`,
        `-/deno.land/x/aleph/error.js`,
        `-/deno.land/x/aleph/events.js`,
        `-/deno.land/x/aleph/routing.js,`,
        `-/deno.land/x/aleph/util.js`
    ]
    return scripts.map(src => ({ src: `${baseUrl}${src}`, type: 'module', preload: true }))
}
```
then inject it to all the `createHtml` calls:
```javascript
createHtml({
    ...
    scripts: [
        ...
        ...getPreloadScripts(baseUrl),
        ...
    ],
    ...
})
```
then i will marge this request, thanks

**Comment by shadowtime2000** [comment]
@ije Done.

**Comment by ije** [comment]
LGTM; thanks

**Pull request merged**
